go-jira/jira

- jira/cli/templates.go
The default view template was failing with this error whenever I tried to
view a jira that had no assignee:
assignee: 2015-02-16T08:31:58.564-08:00 ERROR [util.go:109] Failed to execute template: template: template:7:20: executing "template" at <.fields.assignee.nam...>: nil pointer evaluating interface {}.name
> default view template shouldn't fail when assignee is nil

- jira/main.go
"take" was simply a partial on "assign", but accidentally used the value
of $USER from the environment rather than `opts["user"]`, preventing the
user from overriding this value in config.yml or as a command-line
argument.
> fix "take" command not honouring user option

- jira/cli/commands.go
- jira/main.go
This closes #10
Shifts the hardcoded maxResults value for the cmdList json body
into a 'max_results' option.
Note that testing against our JIRA instance, in a project with
more than 1000 open issues, suggests that the JIRA has an internal
limit of 1000 results in a single query.
> Add --max_results option for 'ls'

- README.md
- jira/cli/util.go
- jira/main.go
I've included the 'updated' field into the default query fields, as it seemed like an oversight, and I need it :)
In the process, noticed that export-templates was broken due to a typo, so fixed that.
I've added a dateFormat template helper, so I can get the create/update time in a more report friendly form.
> Add 'updated' to queryfields; dateFormat template command; bug fix.

- util.go
I needed this so that I can display JIRA labels in my 'list' template, but it should be generally useful.
Happy to have this pushed back for a more robust implementation with tests.
> Add a 'join' func to the template engine

- cli.go
- commands.go
- main/main.go
- util.go
I've added exposed versions of runTemplate and getTemplate, so I can access the template engine with my own Buffer. I opted to add tandem RunTemplate and GetTemplate, rather than a search-replace fix, to make the smallest change possible. Happy to rework if you're not fussed about changing the internal API.
I've split the API-integrated part of `CmdView` into `ViewIssue(...)` as per `FindIssues(...)`.
These are the only exposures I need right now, let me know if you'd like anything else included.
> Expose key functionality for library consumption

- commands.go
- main/main.go
This adds 'labels' command, which allows for the setting, addition and removal
of labels on an issue.
'set' action resets the issue labels to the list provided.
'add' action adds the supplied labels to the issue
'remove' action removes the supplied labels from the issue
The API already gracefully handles duplication, removal of non-existant labels, and the
supplying of an empty list of labels (which is useful in the case of 'set')
Eg
jira labels TEST-123 add label1 label2 label3
jira labels TEST-123 remove label1 label2
jira labels TEST-123 set label1 label2 label3
jira labels TEST-123 set # clears any labels on the issue
jira labels TEST-123 add # no-op
jira labels TEST-123 remove # no-op
This mirrors the functionality of the API.
> Add 'labels' command to set/add/remove labels

- cli.go
- commands.go
- main/main.go
This adds support for voting on issues via CmdVote() and CmdUnvote()
Voting on issues is always done as the logged in user, it appears you
can't case a vote for another user:
https://docs.atlassian.com/jira/REST/latest/#api/2/issue-addVote
This required adding a cli.delete() handler, naturally with no content
(as per RFC2616)
This is ripe for DRY-ing out, but I will leave that for a future PR.
Worth noting is that you cannot vote for your own issues, this results in:
2016-01-13T21:35:41.315Z ERROR [cli.go:184] response status: 404 Not Found
2016-01-13T21:35:41.315Z ERROR [commands.go:439] Unexpected Response From POST:
{snip}
{"errorMessages":["You cannot vote for an issue you have reported."],"errors":{}}
> Add 'vote' and 'unvote'

- cli.go
- commands.go
- main/main.go
As per discussion in #26 -- here is 'remove watcher' support, eg:
jira watch EXAMPLE-123 --watcher bob --remove
I've exposed GetOptString and GetOptBool in the same manner as before - leave the private function intact, just add a public wrapper.
I've mentioned in the commit, but I've expressly not included 'remove: false' as a default option, since at the moment this is specific to 'watch' command. Maybe if we find other reasons to add '--remove' we can promote it.
NOTE: this commit involves a breaking change to the CmdWatch contract, in that it now takes the watcher and whether to remove as arguments. I think i'm the only consumer of this as a library right now, so this is likely not a big problem.
> Support for removing a given watcher

- commands.go
- main/main.go
- templates.go
This adds the basics of the component API:
* listing of components assigned to a project
* adding new components to a project.
The interface to 'add component' is similar to that of 'labels', as
previously discussed. We can implement remove/update later.
> Add component/components support: add and list for now.

- cli.go
TL;DR, this ensures ~/jira.d is present, with 0755 perms.
If `~/jira.d` isn't present, we can't write to the cookieFile, which
breaks CmdLogin. This is particularly an issue when using `/etc/go-jira.yml`
to get an entire team using go-jira easily :)
This fixes this by ensuring the cookieFile dir is present before
writing to it.
> Fixes #32 - make path to cookieFile if it's not present

- commands.go
It is valid within JIRA to have issue types with spaces (for example we use "Pro-Active Task") however the `issuetype` variable is not escaped prior to formatting into the `uri` string.
This fix imports `net/url` and escapes all inclusions of `issuetype` into `uri`. The only other variables formatted into `uri` are `c.endpoint` and `issue` which shouldn't contain special characters.
> Fix issuetype calls adding URL escaping

- README.md
go-jira/jira isn't a proper path.
> Fix path for installation instructions

- cli.go
- main/main.go
The ```expand``` option is used to specify resource expansion in the
Jira REST API.
It's particularly useful for things like fetching the ```changelog``` of
an Issue.
This PR adds the support to the ```ListIssues``` and ```ViewIssue```
functions of the ```jira.Cli``` struct.
I'm happy to add tests, but there is currently no test suite in the
master branch, so I did not want to bog down the PR with tangential features.
> Added support for the ```expand``` option for Issues

- README.md
For a new user, the obvious first step is to configure a server and log in, but only the first half of this was mentioned. Trying to use non-read-only commands like `watch` before that just yields an opaque error, rather than prompting you to log in (0.1.0):
```
… INFO  [cli.go:145] POST https://…/rest/api/2/issue/…/watchers
… ERROR [cli.go:198] response status: 500 Internal Server Error
… ERROR [commands.go:443] Unexpected Response From POST:
HTTP/1.1 500 Internal Server Error
Connection: close
Transfer-Encoding: chunked
Cache-Control: no-cache, no-store, no-transform
Content-Type: application/json;charset=UTF-8
Date: …
Server: Apache-Coyote/1.1
Via: 1.1 …
X-Arequestid: …
X-Asen: …
X-Asessionid: …
X-Ausername: anonymous
X-Content-Type-Options: nosniff
37
{"errorMessages":["Internal …
```
> Noting jira login

- cli.go
- util.go
I've found that several of the built-in templates need a bit of work
to be useful with our JIRA installation (eg #24), so this allows for admins
to make a site-specific set of defaults easily.
> Include templates from a system path

- templates.go
Support the lowest common denominator for default_edit_template, as per #23
`reporter` is not usually editable by unprivileged users. Even if it is left as-is,
the PUT request is trying to update it, resulting in the following error:
{"errorMessages":[],"errors":{"reporter":"Field 'reporter' cannot be set. It is not on the appropriate screen, or unknown."}}
Commenting out the field leaves the information visible, so is a reasonable compromise.
> Reporter is not generally editable.

- commands.go
Some transitions are substrings of other transitions, and the current loop sometimes doesn't choose the best match. For example, it would never choose "QA" if there were also a transition "Deploy to QA". Ditto for "Open" and "Reopen".
> Prefer transition names which match exactly

- cli.go
- main/main.go
- unixproxy.go
Hi there!
We use client certificate authentication, and have a running local proxy on our laptops that allows us to proxy to our internal services, such as JIRA. This is accomplished by shadowing the transport with a custom dialer. It works on my machine :sparkles:. I'm inexperienced with Go a bit, so please advise if I'm doing something absurd!
1. Adds a unixproxy.go file which implements a transport with a shadow to use a unix socket
2. Adds a `unixproxy` configuration option to point to an path on the computer to use
3. If configured, uses the unix proxy as a transport for all http requests
Thanks!
> Add support for a unix socket proxy

- cli.go
Cory, thanks a lot for your excellent tool! I found that "jira browse" did not do anything on Windows yet. I added the missing code to Browse() in cli.go. Hope the change makes sense. (I am a total Go newbie, so there is a good chance I am missing something.)
> Implement "browse" subcommand on Windows

- commands.go
- main/main.go
This allows adding generic links, and could replace 'blocks', and 'dups'
command, since it's pretty much just a copy/paste job.
Usage will be something like:
`$ jira issuelink $INWARDISSUE "Relates" OUTWARDISSUE`
Pulling the list of the names, for your issuelinktypes
```
$ jira issuelinktypes | jq '.issueLinkTypes | map(.name)'
[
"Blocks",
"Bonfire testing",
"Clones",
"Deprecates",
"Duplicate",
"Relates",
"Risks"
]
```
> Added generic issuelink command

- keyring.go
github.com/tmc/keyring returns keyring.ErrNotFound instead of a blank password in newer libraries. Handle this case properly by nulling the error, to give the user a chance to set a new password.
This makes go-jira compatible with the newer versions which now incorporate a fix for working out-of-the-box on Linux.
> Handle keyring.ErrNotFound error instead of panicing.

- issue.go
In #34 a fix was made to escape the issue type to support issue types
with spaces in. This is an additional place where the issue type needs
escaping, otherwise you get 400 Bad Request when trying to create an
issue for an issuetype that has a space in.
> Add URL escaping to an additional issuetype call

- jiracli/templates.go
It add a regRepace function to the template functions.
Have a template like `{{ .fields.description | regReplace "foo" "bar" }}`
Alot of out Tickets are created via email.
Jira often creates double newlines, one for \n and one for \r, also People tend to use a lot of newlines in Email.
This results in tickets, larger than one full screen terminal, containing mostly newlines.
To solve this, and have simple but powerful code i decided to implement regexReplace instead of this specific behavior.
> Add regexReplace template function

- jiracli/cli.go
- jiracli/socksproxy.go
Adds support for using a socks5 proxy.
> add support for using socks proxy

- jiracli/templates.go
check for `.fields.priority` and use `<unassigned>` if it doesn't exist
> prevent crash if priority is not set

- Makefile
Ubuntu 16.04 has go PPAs for the latest version, but does not link them to /usr/bin/go. As a result to use any other version of go than the default requires full path to go.
Per the standards used for c and c++ this adds a $GO variable which defaults to `go` which can be passed in via env var for a specific version of go.
Example:
```
export GO=/usr/lib/go-1.9/bin/go
$ make
/usr/lib/go-1.9/bin/go build -gcflags="-e" -v -ldflags "-w -s" -o '/home/asomerville/go/src/gopkg.in/Netflix-Skunkworks/go-jira.v1/jira' cmd/jira/main.go
command-line-arguments
```
> make it easier to compile with aribtrary version of go via GO env var

- jiracmd/dup.go
- jiracmd/editmeta.go
- jiracmd/issuelink.go
- jiracmd/labelsAdd.go
- jiracmd/labelsRemove.go
- jiracmd/labelsSet.go
- jiracmd/worklogList.go
Hi, we updated some exported function comments based on best practices from [Effective Go](https://golang.org/doc/effective_go.html#commentary). It’s admittedly a relatively minor fix up. Does this help you?
> Fix function comments based on best practices from Effective Go

- README.md
This will update the README.md to include setting the configuration
option password-name when using pass.
> docs: update pass documentation with password-name

- README.md
This README is huge; the document shouldn't take more than two or three
screens. If we need more docs, they should be linked to and live
elsewhere.
For now, start by removing unnecessary sections. Gitter has been
completely unused since 2017, so remove it. The table of contents also
takes a lot of vertical space, when we don't want to have that much
content to begin with.
Tips on forking are also unnecessary, since that's the same for all Go
projects. Moreover, this is out of date now that the project is a Go
module.
Remove the help output, as that can be obtained extremely easily by just
running 'jira -h'.
Finally, remove the v0-v1 changes, as v0 was last released over three
years ago. It's extremely unlikely that anyone still has to upgrade from
the older version.
> README: trim down the content

- attachment.go
- component.go
- epic.go
- error.go
- fields.go
- issue.go
- jiracmd/request.go
- project.go
- search.go
- session.go
- utils.go
An empty stream isn't valid JSON, so we shouldn't silently ignore it.
> don't use ReadAll when decoding JSON

- README.md
- jiracli/password.go
Allow reading password from stdin in `jira login`. This is useful for
combining the jira tool with other command-line utilities. Fixes https://github.com/go-jira/go-jira/issues/262
> Allow reading password from stdin

- jiracli/templates.go
Worklog entries like
```
$ jira worklog add -m"multiline                                     
test" MyIssue -T1m
```
would produce broken YAML in the current version. This small template change fixes it.
> Fix worklog template for multiline comments

- jiradata/TransitionsFuncs.go
Addresses issue #281 by attempting to choose the exact match if possible.
I am reasonably new to `go`, but believe I have implemented this correctly. That being said, I was unable to determine where the tests for this are written, as well as how to execute those tests. Please feel free to request or make changes as needed, though if you want me to do them you'll have to provide some detail in your instructions so I can understand what you need.
> Choose exact transition match if available

- jiracli/templates.go
These functions simplify creating templates that respect terminal screen sizes and truncating content that overflows the fixed space available.
> Add 'pctOf' and 'fit' template functions

- README.md
- jiracli/cli.go
- jiracli/password.go
Add support to switch out password source binary
There is now a new configuration entry option `password-source-binary`,
which allows to use an alternate binary for the gopass/pass password
source.
If the option is not specified, we will fallback to `pass` (for `pass`)
and `gopass` (for `gopass`).
This fixes #288
> Add support to switch out password source binary

- jiracli/cli.go
- jiracli/password.go
This PR reduces the number of times a password source is invoked to retrieve the api-token during a single run of jira from one for each API request to a single one on the first API request.
This is particularly noticeable when using gopass as a password source with a yubikey whose LED flashes when it is solicited to decrypt the password.
An alternative option I considered was to modify [the oreo pre-callback were `globals.GetPass()` is invoked](https://github.com/go-jira/jira/blob/v1.0.22/jiracli/cli.go#L156) but it required much more changes because at the time it is run, the configuration is not yet loaded and the defaulting on `api-token` for atlassian.net endpoints not evaluated.
> Cache password to avoid invoking password source on each API request with api-token

- README.md
- issue.go
- jiracmd/assign.go
- jiracmd/edit.go
- jiracmd/take.go
- jiracmd/watch.go
- users.go
this commit deprecates the searching ability by username and
instructs user to provide email or display names in commands.
the username parameter has been deprecated completely from v2 and v3
api
Signed-off-by: ldelossa <ldelossa@redhat.com>
> username-deprecation: use email and display names

- jiracmd/transition.go
this commit allows a user to use the more friendly field.Name when
transitioning to states which require custom field inputs.
For example our workflow requires a git pull request field and this is now possible:
```
fields:
"Git Pull Request": https://github.com/example
transition:
id: 711
name: Link Pull Request
```
It is possible this functionality exists in some other way - but could not get it to work without the provided diff. 
Signed-off-by: ldelossa <ldelossa@redhat.com>
> transition: map field name to id

- .travis.yml
this commit removes the parallel test matrix as parallel testing runs
the potention of trampling one another
Signed-off-by: ldelossa <ldelossa@redhat.com>
> cicd: deflake tests

- jiracli/usage.go
See https://github.com/alecthomas/kingpin#supporting--h-for-help
This brings a short option to `--help` like all the other flags)
Tested with:
```
make
./jira -h
```
> Make -h flag show --help

- README.md
This closes #291.
On a fresh go 1.14.1 install on macOS 10.15.3 (19D76), I got the error referenced in #291. This fixed it for me.
> Ensure `GO111MODULE=on` prior to installing

- jiracmd/request.go
Avoid JSON parser when the response is empty - common cases for HTTP 204 in issues deletion, or moving issues to sprint.
Bellow the example of first running with my branch build and second with the last release.
> Support empty responses in request commands

- jiracli/templates.go
- jiracmd/create.go
- jiracmd/subtask.go
addresses go-jira/jira#369
whether we use `emailAddress` here or `displayName` is probably up for debate, but like I said in the above issue, I find `emailAddress` to be more consistent
I also didn't change `displayName` to `emailAddress` in non-edit commands like `view` - this is probably also up for debate
> update templates with emailAddress and login

- go.mod
- go.sum
- jiracli/templates.go
Add "wrap" command to TemplateProcessor.  Use
github.com/mitchellh/go-wordwrap to wrap lines on word breaks at
a given length.  This can make long fields much more readable in
a terminal.  E.g.
{{ .fields.description | wrap 76 | indent 2}}
> templates: add wrap helper function

- jiracmd/block.go
The BLOCKER and ISSUE arguments for the block command were incorrect.
With hypothetical ticket names BLOCKER and ISSUE, calling
jira block BLOCKER ISSUE
resulted in
ISSUE blocks BLOCKER
BLOCKER is blocked by ISSUE
which is the reverse of the documentation which claims it should be
BLOCKER blocks ISSUE
ISSUE is blocked by BLOCKER
Reverse order of the arguments so the documentation matches the
actual usage.  This does not break existing usage, only updates the
documentation.
Fixes #383
> block: reverse order of arguments

- README.md
- jiracli/cli.go
- jiracmd/login.go
- jiracmd/logout.go
Hi, thanks for the neat tool.
For some reason, our private Jira installation requires the Bearer authentication scheme for API tokens, instead of Basic authentication. I don't know the reason - perhaps it's because there is SAML configured.
Anyway, this patch adds support for such configurations.
Cheers
> Add authentication-method: bearer-token

- jiracmd/login.go
Couldn't determine original intention of loop within `CmdLogin`, but ran into an issue locally where a cron job that ran the login command inadvertently got stuck in a failure loop where it continued to make bad requests to the Jira server.
> Remove (possible) infinite loop from CmdLogin.

- jiracmd/rank.go
This looked like an artifact of a copy/paste sorta situation: the current description for the `rank` command has the description for the `block` command.
I ad libbed a new description that is hopefully at least _more_ correct 😄
> Update (miscopied?) description of rank command

- jiracli/templates.go
This function can be used in templates to change the default column
width to accommodate wider terminals.
> feat: add `defaultColWidth` template function

- jiracmd/browse.go
This is done in order to ensure consistency with the other commands on how the configuration files are loaded. I found out about it when I had set up a global project, but the "jira browse 1234" command complained about missing project.
> Load config on "jira browse"
